apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ${var.app-name}-config
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: rook-cephfs-retain