nodes:
  - address: gimli.home
    user: gimli
    role:
      - controlplane
      - etcd
      - worker
    labels:
      accelerator: nvidia
  - address: helium.home
    user: atom
    role:
      - controlplane
      - etcd
      - worker
  - address: lithium.home
    user: atom
    role:
      - controlplane
      - etcd
      - worker
ingress:
  provider: none
  extra_args:
      enable-ssl-passthrough: "true"

kubernetes_version: "v1.32.5-rancher1-1"
enable_cri_dockerd: true

kubelet:
  extra_args:
    # feature-gates: MixedProtocolLBService=true
    container-log-max-files: 5
    container-log-max-size: 10Mi
network:
 plugin: calico
