apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: moonbase-secret-store
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  destination:
    namespace: moonbase-secrets
    server: https://kubernetes.default.svc
  project: default
  source:
    path: moonbase
    repoURL: git@github.com:marklester/moonbase-secrets.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
      - PrunePropagationPolicy=foreground
      - ServerSideApply=true
