apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lidarr-config
  namespace: lidarr
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: rook-cephfs-retain
