apiVersion: apps/v1
kind: Deployment
metadata:
  name: mqtt
  namespace: mqtt
  labels:
    app: mqtt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mqtt
  template:
    metadata:
      labels:
        app: mqtt
    spec:
      containers:
      - name: mqtt
        image: eclipse-mosquitto:2.1.2-alpine
        imagePullPolicy: IfNotPresent
        ports:
        - name: mqtt-tcp
          containerPort: 1883
          protocol: TCP
        volumeMounts:
        - name: data
          mountPath: /mosquitto/data
        - name: mqtt-conf
          mountPath: /mosquitto/config
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: mqtt-config
      - name: mqtt-conf
        configMap:
          name: mosquitto-config
          items:
            - key: mosquitto.conf
              path: mosquitto.conf
