apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qbittorrent-appdata
  namespace: qbittorrent
  annotations:
    argocd.argoproj.io/sync-options: Prune=false  
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: rook-cephfs-retain