apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vpn-credentials
spec:
  secretStoreRef:
    name: main-secret-store
    kind: ClusterSecretStore
  target:
    name: vpn-credentials
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: vpn/username
        version: v1
    - secretKey: password
      remoteRef:
        key: vpn/password
        version: v1
    - secretKey: private-key
      remoteRef:
        key: vpn/private-key
        version: v1
