---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tunarr
  labels:
    app: tunarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tunarr
  template:
    metadata:
      labels:
        app: tunarr
    spec:
      nodeSelector:
          "feature.node.kubernetes.io/amd-apu": "true"
      containers:
        - name: tunarr
          image: ghcr.io/chrisbenincasa/tunarr:1.3.15
          imagePullPolicy: Always
          env:
            - name: TZ
              value: "America/New_York"
            - name: TUNARR_SERVER_TRUST_PROXY
              value: "true"                         
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 10
            failureThreshold: 6
          volumeMounts:
            - name: tunarr-config
              mountPath: /config/tunarr
            - name: tunarr-logs
              mountPath: /config/tunarr/logs
            # - name: dri-card
            #   mountPath: /dev/dri/card0
            - name: dri-render
              mountPath: /dev/dri/renderD128
            - name: streams
              mountPath: /config/tunarr/streams              
          securityContext:
            privileged: true                    
        - name: tunarr-file-logs
          image: victoriametrics/vlagent:v1.52.0
          args:
            - --envflag.enable
            - --envflag.prefix=VL_
            - --fileCollector.glob=/logs/**/*.log*
            - '--fileCollector.extraFields={"cluster":"main","app":"tunarr","log_source":"file","kubernetes.container_name":"tunarr","kubernetes.pod_name":"%{POD_NAME}","kubernetes.pod_namespace":"tunarr"}'
            - --fileCollector.streamFields=cluster,app,kubernetes.pod_namespace,kubernetes.pod_name,kubernetes.container_name,file
            - --fileCollector.decolorizeFields=_msg
            - '--remoteWrite.headers=AccountID:0^^ProjectID:0'
            - --remoteWrite.url=http://victorialogs.moonbase.home/insert/native
            - --tmpDataPath=/var/lib/vlagent
            - --loggerFormat=json
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          volumeMounts:
            - name: tunarr-logs
              mountPath: /logs
              readOnly: true
            - name: tunarr-file-log-vlagent-data
              mountPath: /var/lib/vlagent
          resources:
            requests:
              cpu: 25m
              memory: 128Mi
            limits:
              memory: 256Mi
      volumes:
        - name: tunarr-config
          persistentVolumeClaim:
            claimName: tunarr-config 
        # - name: dri-card
        #   hostPath:
        #     path: /dev/dri/by-path/pci-0000:30:00.0-card
        - name: dri-render
          hostPath:
            path: /dev/dri/by-path/pci-0000:30:00.0-render
        - name: streams
          emptyDir:
            medium: Memory
        - name: tunarr-logs
          emptyDir: {}
        - name: tunarr-file-log-vlagent-data
          emptyDir: {}
