---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tunarr
  labels:
    app: tunarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tunarr
  template:
    metadata:
      labels:
        app: tunarr
    spec:
      nodeSelector:
          "feature.node.kubernetes.io/amd-apu": "true"
      containers:
        - name: tunarr
          image: ghcr.io/chrisbenincasa/tunarr:1.2.8
          imagePullPolicy: Always
          env:
            - name: TZ
              value: "America/New_York"
            - name: TUNARR_SERVER_TRUST_PROXY
              value: "true"                         
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          volumeMounts:
            - name: tunarr-config
              mountPath: /config/tunarr
            - name: dri-card
              mountPath: /dev/dri/card0
            - name: dri-render
              mountPath: /dev/dri/renderD128
            - name: streams
              mountPath: /config/tunarr/streams              
          securityContext:
            privileged: true                    
      volumes:
        - name: tunarr-config
          persistentVolumeClaim:
            claimName: tunarr-config 
        - name: dri-card
          hostPath:
            path: /dev/dri/by-path/pci-0000:30:00.0-card
        - name: dri-render
          hostPath:
            path: /dev/dri/by-path/pci-0000:30:00.0-render
        - name: streams
          emptyDir:
            medium: Memory
