apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: bitwarden-google-drive-backup
  namespace: bitwarden
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: main-secret-store
    kind: ClusterSecretStore
  target:
    name: bitwarden-google-drive-backup
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        RESTIC_REPOSITORY: rclone:gdrive:backups/bitwarden
        RESTIC_PASSWORD: "{{ .password }}"
        RCLONE_CONFIG_GDRIVE_TYPE: drive
        RCLONE_CONFIG_GDRIVE_SCOPE: drive.file
        RCLONE_CONFIG_GDRIVE_CLIENT_ID: "{{ .client_id }}"
        RCLONE_CONFIG_GDRIVE_CLIENT_SECRET: "{{ .client_secret }}"
        RCLONE_CONFIG_GDRIVE_TOKEN: "{{ .token }}"
  data:
    - secretKey: password
      remoteRef:
        key: restic/main-backups/password
        version: v1
    - secretKey: client_id
      remoteRef:
        key: rclone/bitwarden-google-drive/client-id
        version: v1
    - secretKey: client_secret
      remoteRef:
        key: rclone/bitwarden-google-drive/client-secret
        version: v1
    - secretKey: token
      remoteRef:
        key: rclone/bitwarden-google-drive/token
        version: v1
