apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: samba-state
  namespace: samba
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: rook-cephfs
