apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bazarr-config
  annotations:
    # This keeps the PVC even if deleted from Git
    argocd.argoproj.io/sync-options: Prune=false
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: rook-cephfs-retain