apiVersion: v1
kind: ConfigMap
metadata:
  name: home-assistant-2-config
  namespace: home-assistant-2
data:
  configuration.yaml: |
    default_config:

    http:
      use_x_forwarded_for: true
      trusted_proxies:
        - 192.168.0.10
        - 127.0.0.1
        - 10.43.0.0/16
        - 10.42.0.0/16

    homeassistant:
      internal_url: http://home-assistant.home
      time_zone: America/New_York
