apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: home-assistant-2-config
  namespace: home-assistant-2
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: rook-cephfs-retain
  resources:
    requests:
      storage: 20Gi
