apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: soulseek-appdata
  namespace: soulseek
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: rook-cephfs-retain
