apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pig-ebank-ghcr-credentials
  namespace: pig-ebank
spec:
  secretStoreRef:
    name: main-secret-store
    kind: ClusterSecretStore
  target:
    name: pig-ebank-ghcr-credentials
    creationPolicy: Owner
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: |
          {
            "auths": {
              "https://ghcr.io": {
                "username": "{{ .ghcrUsername }}",
                "password": "{{ .ghcrApiKey }}",
                "email": "{{ .email }}",
                "auth": "{{ b64enc (printf "%s:%s" .ghcrUsername .ghcrApiKey) }}"
              }
            }
          }
  data:
    - secretKey: ghcrUsername
      remoteRef:
        key: ghcr/username
        version: v1
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        nullBytePolicy: Ignore
    - secretKey: ghcrApiKey
      remoteRef:
        key: ghcr/api-key
        version: v1
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        nullBytePolicy: Ignore
    - secretKey: email
      remoteRef:
        key: email
        version: v1
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        nullBytePolicy: Ignore
