---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-smtp-credentials
  namespace: monitoring
spec:
  encryptedData:
    password: AgAAGVWjJiTV/Q1h4kzq1ksHsaHNUF81zfmrM0xsyASG4nCVP0ExNwD3GYw1PPj+ENKhPEXMjW1uY6VcAcDKssH0a3w7ZwDm1izPShGbjCxQ70nYyIrXiPCnWsgU6461ZQikwFZkhQ1m/f97JotnN64xsfWUNcJtfeT3D4gcLv9Sm9L+aSpd311/S04odR7xIJkkIWKp6y+hXbjsThI3XfkhNAQXcZFigR6hnMUdjB0bWnzinjEyDY9OEQGwr/ndiWU+wfhrMUUEOadBmDJBkQNFNYTn2G6azQta1NqBO614KKrLVP80zEKNyAfTpY3sC9wzMSt5DXDBAejpOBqF0CLwf+AtYSdkL6J0r0ubf9ZM3lx4Q9uM+WlI7NQTreY5QlTZgjWCL1i/6eRoPksMbnLbya9Dc+Z7kR7KGmufQMCM4RVSepVG+hIBlG8PzoSxcmA0mlSMXJe913NRg2KEz+iWAaiT6EjQDCa+kIz+wCq67OYa+gfaBSI6kbjwZXiOAFremQieDLY/p969LoeiwA9c3eXerh/+ro0Pnu14rNGe1oRza3wOTCfKpy7qMBFs3NNhCdP0CKGlq7IysSWI7G8BzOGsg55eQPhTXlBMOsRB3kvjoS0kxRs6WT6u8ZBEo/DamUOJQEHf+yfPfANXFf3wuiHFyn6dxzjNqj5xFd4390VqOLasJCc65wnNWyz2PPVXh8fMuRbSt1HOgI/GccuQ
    user: AgAEXITTZ8kOysD8uBT1LRNZ8vBvcTgwI2tU3YJxIueEOcDX2LswbcUAZcwW56mubJmGYdNSeqjTw9s9ZZ3NDTAEHC/F7ZnKAv7CT0a+FbeznEVuucAQ+pQJGzYTYNzcJDXobhbfepEnwcIGJqbH35emyfq6FNGGSUf9DOaab3KIPFwUL/ngenx/+7FOGQjEXjIju8ufLPmb2uwDZVyIN2lKnuf+Ei4q14e1MpvE8SaFJd6qg4T95INysuUjRdUgMeOdQnzWnJQirjQt6LIqKCNstbYhAbY9+vF308CblD5SFBD8CBM5ZcOZIT2ihZKMmXWymFQ9/MTMyu7hV2FRutWWDv7oDkpBvyYuOd9eRXsGZWC3ABZFQxzCBNVwa5EgrWuRUNrStCesndL8LVUJ3KDdqdfF97JVT93uzOGoudxKK7jEb/oxjZ4u5R7XqQjta0qFuDgzO0mPwY3xbBII7ikPcIAjQz4PX4284aMPC0uhEiuZ0Vii74dr3RCOwQ9VSRmz+muLUWRPtppzVZr6h5Wxc0nA1e9up3Ip8mDA3OfiitRFhw2ML/ulEsfVRQ2OT1MCAi3LRdz779pQa9tCQ5g6GCRuGc1uwLXNLxeazoN1lkEkNGIWtA3oMyR+xJUU9EWkS2npCbtwLDpRwA9L65OLwJcG+2lcANoUWA8tKABwcjfpVvt+Zo2DdVk+Q7Dc29/J1i6/LHgWyj0+6ngJbv82WA==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-smtp-credentials
      namespace: monitoring
