# https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack
# helm install kube-prometheus-stack prometheus-community/kube-prometheus-stack -f values.yaml
# helm upgrade kube-prometheus-stack prometheus-community/kube-prometheus-stack -f values.yaml
namespaceOverride: monitoring

alertmanager:
  enabled: false

grafana:
  enabled: true
  namespaceOverride: monitoring
  persistence:
    enabled: true
    type: pvc
    storageClassName: rook-cephfs-retain
    accessModes:
    - ReadWriteMany
    size: 4Gi
  service: 
    type: LoadBalancer
    loadBalancerIP: "192.168.0.209"
prometheusOperator:
  certManager:
    enabled: true

prometheus:
  service: 
    type: LoadBalancer
    loadBalancerIP: "192.168.0.202"
  
  prometheusSpec:
    scrapeInterval: 30s
    evaluationInterval: 30s
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false
    retention: 14d
    retentionSize: 85GB
    additionalScrapeConfigs:
    - job_name: gpu-metrics
      scrape_interval: 30s
      metrics_path: /metrics
      scheme: http
      kubernetes_sd_configs:
      - role: endpoints
        namespaces:
          names:
          - gpu-operator-resources
      relabel_configs:
      - source_labels: [__meta_kubernetes_pod_node_name]
        action: replace
        target_label: kubernetes_node    
  
    storageSpec: 
      ## Using PersistentVolumeClaim
      ##
      volumeClaimTemplate:
        spec:
          storageClassName: rook-cephfs
          accessModes: ["ReadWriteMany"]
          resources:
            requests:
              storage: 100Gi
    securityContext:
      runAsUser: 1000
      runAsGroup: 2000
      runAsNonRoot: true
      fsGroup: 1000
      seccompProfile:
        type: RuntimeDefault              
    # initContainers:
    #   - name: chown
    #     image: busybox:stable
    #     command: [chmod, -R, "777", /prometheus]
    #     volumeMounts:
    #       - mountPath: /prometheus
    #         name: prometheus-kube-prometheus-stack-prometheus-db
    #         subPath: prometheus-db   
prometheus-node-exporter:
  namespaceOverride: monitoring

kubeStateMetrics:
  enabled: true
kube-state-metrics:
  namespaceOverride: monitoring