apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-admin-credentials-eso
  namespace: monitoring
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: moonbase-secret-store
    kind: ClusterSecretStore
  target:
    name: grafana-admin-credentials-eso
    creationPolicy: Owner
  data:
    - secretKey: admin-user
      remoteRef:
        key: grafana/admin/username
        version: v1
        decodingStrategy: Base64
    - secretKey: admin-password
      remoteRef:
        key: grafana/admin/password
        version: v1
        decodingStrategy: Base64
