apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-smtp-credentials-eso
  namespace: monitoring
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: moonbase-secret-store
    kind: ClusterSecretStore
  target:
    name: grafana-smtp-credentials-eso
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: grafana/smtp/username
        version: v1
        decodingStrategy: Base64
    - secretKey: password
      remoteRef:
        key: grafana/smtp/password
        version: v1
        decodingStrategy: Base64
